In [ ]:
import numpy as np
np.__version__

'1.25.2'

### Matrix and vector products

The following array represents the grades from 5 students in 4 tests applied along a semester.

In [ ]:
rng = np.random.default_rng(seed=5)

In [ ]:
scores = np.clip( # limits the grade in the interval [0, 10]
    a=np.round( # rounds the grades to 1 decimal point
        a=rng.normal(loc=7, scale=2, size=20), # samples numbers from a normal distribution
        decimals=1
        ),
    a_min=0,
    a_max=10
).reshape(5, 4) # reshapes to the desired shape

In [ ]:
scores

array([[ 5.4,  4.4,  6.5,  7.8],
       [ 9.3,  7.2,  5.9,  5.4],
       [ 8.5, 10. ,  7.5,  4.5],
       [ 5.1, 10. ,  7.4,  3.5],
       [ 6.8,  4.7,  5.7,  6. ]])

👆 5 students (5 rows), 4 grades (4 columns).

To generate the average, the teacher decided to apply different weights to each test, according to the array below.

In [ ]:
weights = np.array([[0.2],
                    [0.3],
                    [0.4],
                    [0.1]])

In [ ]:
weights

array([[0.2],
       [0.3],
       [0.4],
       [0.1]])

#### `np.dot`

Use `np.dot` to calculate the product between matrices `scores` and `weights`.

In [ ]:
...

array([[5.78],
       [6.92],
       [8.15],
       [7.33],
       [5.65]])

Note that the result represents the **weighted average** of the students.

#### `np.vdot`

Use indexing to get the notes for student indexed 2 in a new variable.

In [ ]:
scores_2 = ...

In [ ]:
scores_2

array([ 8.5, 10. ,  7.5,  4.5])

Now use `np.vdot` to determine the average grade for student 2. Remeber that, since this function accepts only vectors, you must linearize `weights`, because it is formatted as a matrix. You can use either methods `ravel` or `flatten`, and you can apply the method to `weights` directly from within the `np.vdot` function.

In [ ]:
...

8.15

Note that this is the same result obtained for student 2 in the exercise using `np.dot`.

####  `np.inner`

Redo the same calculation but now using the `np.inner` function.

In [ ]:
...

8.15

Remember that, for two vectors, the `inner` product is equal to the vector product (`dot` or `vdot`).

#### `np.matmul`

Once more redo the calculation, now using `np.matmul`.

In [ ]:
...

8.15

The "matrix" multiplication between two vector does also correspond to the vector product between them.

#### `np.outer`

This function is useful when we want to obtain a matrix from the multiplication of two vectors, where the values are obtained from the multiplication of all values in the vectors.

Given the vectors below:

In [ ]:
array_0 = np.array([2, 3, 7])
array_1 = np.array([0.7, 0.2, 0.3, 0.4])

Determine the matrix that is obtained by the calculation mentioned above.

In [ ]:
...

array([[1.4, 0.4, 0.6, 0.8],
       [2.1, 0.6, 0.9, 1.2],
       [4.9, 1.4, 2.1, 2.8]])

Observe that the matrix's shape reflects the length of the vectors: 3x4.

#### `np.linalg.det`

The determinant of a matrix is used to calculate the inverse of the matrix.

Calculate the determinant of the following matrix:

In [ ]:
array_2 = rng.normal(loc=5, scale=2, size=16).reshape(4, 4)

In [ ]:
array_2

array([[3.57337326, 6.10675694, 4.87382806, 3.82113748],
       [5.81927565, 6.65971061, 1.71395326, 4.48653975],
       [3.03850529, 4.65368955, 2.42116251, 5.04138079],
       [4.92422852, 4.3913245 , 2.90414699, 4.20761934]])

In [ ]:
...

101.71871198583534

#### `np.linalg.inv`

But you can also obtain the inverse directly from the fuction `np.linalg.inv`. Do this for `array_2`.

In [ ]:
array_2_inv = ...

In [ ]:
array_2_inv

array([[-0.12133586,  0.03653967, -0.30410658,  0.43559582],
       [ 0.18856179,  0.30405942,  0.00121017, -0.49690715],
       [ 0.21974751, -0.27338361, -0.12332989,  0.2397113 ],
       [-0.20646582, -0.17140502,  0.43976035,  0.08103165]])

Use `np.matmul` to confirm that the matrix multiplication between a matrix and its inverse results in the identity matrix, where the values in the diagonal equal 1, and all others are 0.

In [ ]:
array_mul = ...

In [ ]:
array_mul

array([[ 1.00000000e+00, -2.28370863e-16, -4.34034021e-17,
        -1.88323981e-16],
       [-1.56417331e-16,  1.00000000e+00,  2.45108307e-16,
         3.63683316e-17],
       [-1.72780463e-16, -2.91534209e-16,  1.00000000e+00,
        -1.67128393e-16],
       [ 3.04949725e-17, -3.01842060e-16, -1.31248302e-16,
         1.00000000e+00]])

These values are difficult to interpret because of the rounding operations performed by NumPy.

Let's instantiate an identity matrix with the same shape as `array_mul`. This is done with the function `np.identity`.

In [ ]:
array_identity = ...

In [ ]:
array_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Finally, use `np.allclose` to verify that indeed the values in `array_mul` are virtually equal to `array_identity`.

In [ ]:
...

True