In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.25.2'

In this module, we will work with a 3-D array, which represents the performance of running athletes.

In the first dimension (depth), we will represent 3 different evaluation days. In the second dimension (rows), each of the 5 athletes. In the third dimension (columns), each of the 4 laps of the race track. Values ​​will be given in seconds.

This data will be simulated with the code below, but don't worry about understanding it for now, the details of these functions will be presented in the next classes.

In [ ]:
rng = np.random.default_rng(seed=1)

In [ ]:
rng

Generator(PCG64) at 0x7F2590D1B4C0

In [ ]:
array = rng.normal(loc=50, scale=3, size=60).reshape(3, 5, 4).round(3)

In [ ]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [ ]:
array.shape

(3, 5, 4)

In [ ]:
3 * 5 * 4

60

In [ ]:
array.size

60

👆 Notice from the `shape` that there are 3 days, 5 athletes and 4 laps.

Given the definition of this array presented above, you can understand the very first row:
```
[51,037, 52,465, 50,991, 46,091]
```
as the performance of the first athlete, on the first day, in the 4 laps of the track.

The seventh row:
```
[41,867, 44,333, 49,476, 48,733]
```
is the performance of the second athlete (second row of that "bunch") on the second day (second "bunch"), in the 4 laps of the track.

### Indexing

Given the array above, use indexing to retrieve the performance of the third athlete on the second day.

Remember that in Python, indexing starts at 0!

In [ ]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [49.705, 50.286, 50.107, 48.481],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

In [ ]:
array[...]

array([50.641, 50.652, 56.354, 46.664])

Now recover the performance of all athletes in the last lap of the first day. Use negative indexing to access the last lap.

In [ ]:
...

array([46.091, 51.743, 51.64 , 51.797, 49.228])

Now recover the performance of the second and fourth athletes, on the third day, in the second lap.

In [ ]:
...

array([50.286, 48.496])

Using negative indexing, recover the performance of all athletes on all days, on the penultimate lap.

In [ ]:
...

array([[50.991, 48.389, 50.085, 48.554, 47.654],
       [53.882, 49.476, 56.354, 51.94 , 50.502],
       [49.784, 50.107, 50.963, 52.637, 46.254]])

Create a boolean mask to represent only the results less than 46. Then use this mask to filter the results from the array that meet this condition.

In [ ]:
mask = ...

In [ ]:
mask

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [ True,  True, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False,  True, False, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]])

In [ ]:
...

array([41.867, 44.333, 45.056])

### Slicing

Use slicing to recover the fourth athlete's performance in the first two laps, on all days.

In [ ]:
...

array([[47.791, 49.511],
       [48.867, 56.128],
       [52.195, 48.496]])

Now recover the performance of all athletes in the first two days, from the second lap onwards.

In [ ]:
...

array([[[52.465, 50.991, 46.091],
        [51.339, 48.389, 51.743],
        [50.882, 50.085, 51.64 ],
        [49.511, 48.554, 51.797],
        [49.123, 47.654, 49.228]],

       [[49.173, 53.882, 53.02 ],
        [44.333, 49.476, 48.733],
        [50.652, 56.354, 46.664],
        [56.128, 51.94 , 51.989],
        [45.056, 50.502, 50.327]]])

Use negative and step notation to retrieve the performances of the last two athletes, on the second day, in the laps odd-indexed.

In [ ]:
...

array([[56.128, 51.989],
       [45.056, 50.327]])

### Assigning

Suppose the second athlete was disqualified in the third day's race, and you must demonstrate this in the array by changing all the values ​​of his laps to the number 99.

Use the assigning technique to make this correction, and display the modified array.

In [ ]:
array[...] = ...

In [ ]:
array

array([[[51.037, 52.465, 50.991, 46.091],
        [52.716, 51.339, 48.389, 51.743],
        [51.094, 50.882, 50.085, 51.64 ],
        [47.791, 49.511, 48.554, 51.797],
        [50.119, 49.123, 47.654, 49.228]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.   , 99.   , 99.   , 99.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

It was discovered that the stopwatch used on the first day of the race was discalibrated, and therefore, all corresponding times must be increased by 0.05 seconds. Perform the correction and display the modified array.

Remember that you can add values ​​to a Python object with the `+=` notation.

In [ ]:
array[0]

array([[51.037, 52.465, 50.991, 46.091],
       [52.716, 51.339, 48.389, 51.743],
       [51.094, 50.882, 50.085, 51.64 ],
       [47.791, 49.511, 48.554, 51.797],
       [50.119, 49.123, 47.654, 49.228]])

In [ ]:
...

In [ ]:
array

array([[[51.087, 52.515, 51.041, 46.141],
        [52.766, 51.389, 48.439, 51.793],
        [51.144, 50.932, 50.135, 51.69 ],
        [47.841, 49.561, 48.604, 51.847],
        [50.169, 49.173, 47.704, 49.278]],

       [[50.024, 49.173, 53.882, 53.02 ],
        [41.867, 44.333, 49.476, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.   , 99.   , 99.   , 99.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])

The third lap of the first two athletes on the second day was recorded wrong, the correct values ​​are 53.872 and 49.479. Make the correction and display the modified array.

In [ ]:
array[...] = ...

In [ ]:
array

array([[[51.087, 52.515, 51.041, 46.141],
        [52.766, 51.389, 48.439, 51.793],
        [51.144, 50.932, 50.135, 51.69 ],
        [47.841, 49.561, 48.604, 51.847],
        [50.169, 49.173, 47.704, 49.278]],

       [[50.024, 49.173, 53.872, 53.02 ],
        [41.867, 44.333, 49.479, 48.733],
        [50.641, 50.652, 56.354, 46.664],
        [48.867, 56.128, 51.94 , 51.989],
        [48.458, 45.056, 50.502, 50.327]],

       [[46.318, 47.95 , 49.784, 47.166],
        [99.   , 99.   , 99.   , 99.   ],
        [51.781, 52.674, 50.963, 47.545],
        [52.195, 48.496, 52.637, 46.785],
        [52.743, 49.94 , 46.254, 49.058]]])