In [ ]:
import numpy as np
np.__version__

'1.25.2'

Start by generating two arrays:
- the first through sampling from a normal distribution with mean 10 and standard deviation 2, in the 5x3 format.
- the second through sampling from a uniform distribution with a minimum of 25 and a maximum of 50, in the 3x4x2 format.

To ensure reproducibility, use seed equal to 10.

In [ ]:
rng = ...

In [ ]:
array_1 = ...

In [ ]:
array_1

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

In [ ]:
array_2 = ...

In [ ]:
array_2

array([[[48.33596177, 28.62486737],
        [43.63950528, 28.48378485],
        [47.6632189 , 30.65286084],
        [46.33099375, 32.65794664]],

       [[49.24575921, 37.94585534],
        [33.06186397, 32.06083793],
        [40.1466249 , 33.34411142],
        [41.96621934, 28.86062676]],

       [[31.24438798, 46.74735615],
        [40.00919551, 31.5495764 ],
        [28.73537251, 28.41972874],
        [31.22302344, 34.57061666]]])

#### `np.save`, `np.load`

Save `array_1` in a file called `array_1_file`.

In [ ]:
...

Reload the array from the file.

In [ ]:
array_1_loaded = ...

In [ ]:
array_1_loaded

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

Check that the two arrays are equal with `np.array_equal`.

In [ ]:
...

True

#### `np.savez`

Save both arrays in a single `npz` file.

In [ ]:
...

Reload the file and restore both arrays.

In [ ]:
arrays_loaded = ...

In [ ]:
arrays_loaded

NpzFile 'arrays_savez.npz' with keys: arr_0, arr_1

In [ ]:
array_1_loaded = ...

In [ ]:
array_1_loaded

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

In [ ]:
array_2_loaded = ...

In [ ]:
array_2_loaded

array([[[48.33596177, 28.62486737],
        [43.63950528, 28.48378485],
        [47.6632189 , 30.65286084],
        [46.33099375, 32.65794664]],

       [[49.24575921, 37.94585534],
        [33.06186397, 32.06083793],
        [40.1466249 , 33.34411142],
        [41.96621934, 28.86062676]],

       [[31.24438798, 46.74735615],
        [40.00919551, 31.5495764 ],
        [28.73537251, 28.41972874],
        [31.22302344, 34.57061666]]])

#### `np.savez_compressed`

Save both arrays in a single compressed file, then reload.

In [ ]:
...

In [ ]:
arrays_compacted_loaded = ...

In [ ]:
arrays_compacted_loaded

NpzFile 'arrays_compacted.npz' with keys: arr_0, arr_1

#### `np.savetxt`, `np.loadtxt`

Save `array_1` in `csv` format.

In [ ]:
...

Use the Linux command below to view how the data was saved to the file.

In [ ]:
!head array_csv.csv

7.793323101868935510e+00 8.549950719511119956e+00 8.436389485363886109e+00
1.053395171278878450e+01 9.502838541122217819e+00 1.025296610302370048e+01
1.168608514160867529e+01 1.171587309895153695e+01 1.095036728389717062e+01
9.098462803835166923e+00 8.490135436352497678e+00 8.370371785321818692e+00
9.312290284411478325e+00 9.897239812426132488e+00 8.055452645251286015e+00


Reload this array from the file.

In [ ]:
array_1_loaded = ...

In [ ]:
array_1_loaded

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

Use `np.array_equal` to verify that even when saved as `csv`, the reloaded array is equal to the original array.

In [ ]:
...

True