In [ ]:
import numpy as np
np.__version__

'1.25.2'

### Grouping and splitting arrays

#### `np.concatenate` / `np.stack` / `np.vstack` / `np.hstack`

First use `np.arange` and `reshape` to create a 2D array with values ​​between 0 and 1, and step equal to 0.1, organized as a matrix of 2 rows and 5 columns.

In [ ]:
array_0 = ...

In [ ]:
array_0

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

Now create a second array with values ​​between 1 and 2, and step 0.1, in the same format.

In [ ]:
array_1 = ...

In [ ]:
array_1

array([[1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

Use `np.concatenate` to concatenate the two arrays along the rows, that is, axis 0.

In [ ]:
...

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

👆 Notice that the new array now has 4 rows and 5 columns.

Use `np.vstack` to stack the two arrays vertically, and notice that the result is the same as that of `np.concatenate` with `axis=0`.

In [ ]:
...

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

Use `np.stack` to stack the two arrays on axis 0, but note that in this case, a new dimension is created.

In [ ]:
...

array([[[0. , 0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8, 0.9]],

       [[1. , 1.1, 1.2, 1.3, 1.4],
        [1.5, 1.6, 1.7, 1.8, 1.9]]])

Now repeat the procedure regarding axis 1. In this case, you must use `np.hstack`.

In [ ]:
...

array([[0. , 0.1, 0.2, 0.3, 0.4, 1. , 1.1, 1.2, 1.3, 1.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 1.5, 1.6, 1.7, 1.8, 1.9]])

In [ ]:
...

array([[0. , 0.1, 0.2, 0.3, 0.4, 1. , 1.1, 1.2, 1.3, 1.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 1.5, 1.6, 1.7, 1.8, 1.9]])

In [ ]:
...

array([[[0. , 0.1, 0.2, 0.3, 0.4],
        [1. , 1.1, 1.2, 1.3, 1.4]],

       [[0.5, 0.6, 0.7, 0.8, 0.9],
        [1.5, 1.6, 1.7, 1.8, 1.9]]])

### Adding axes

#### `np.expand_dims`

Add a dimension on axis 0 of `array_0`.

Display the resulting array and its `shape` to observe the effect this operation had.

In [ ]:
array_0_ed_0 = ...

In [ ]:
array_0_ed_0

array([[[0. , 0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8, 0.9]]])

In [ ]:
...

(1, 2, 5)

Now repeat for axis 1.

In [ ]:
array_0_ed_1 = ...

In [ ]:
array_0_ed_1

array([[[0. , 0.1, 0.2, 0.3, 0.4]],

       [[0.5, 0.6, 0.7, 0.8, 0.9]]])

In [ ]:
...

(2, 1, 5)

Repeat for axis 2.

In [ ]:
array_0_ed_2 = ...

In [ ]:
array_0_ed_2

array([[[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4]],

       [[0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9]]])

In [ ]:
...

(2, 5, 1)

### Rearranging elements

#### `np.flip`

Invert `array_0`, displaying the result to visualize the change.

In [ ]:
...

array([[0.9, 0.8, 0.7, 0.6, 0.5],
       [0.4, 0.3, 0.2, 0.1, 0. ]])

👆 The rows and columns have been reversed.

Invert `array_0` only on axis 0.

In [ ]:
...

array([[0.5, 0.6, 0.7, 0.8, 0.9],
       [0. , 0.1, 0.2, 0.3, 0.4]])

👆 Only the rows were reversed.

Invert `array_0` only on axis 1.

In [ ]:
...

array([[0.4, 0.3, 0.2, 0.1, 0. ],
       [0.9, 0.8, 0.7, 0.6, 0.5]])

👆 Only the columns were reversed.

#### `np.resize`

Resize `array_0` to linearized format with 8 elements.

In [ ]:
...

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])

👆 As the new size is smaller than the previous one, the original array is truncated.

Resize `array_0` to linearized format with 15 elements.

In [ ]:
...

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0. , 0.1, 0.2,
       0.3, 0.4])

👆 As the new size is larger than the previous one, the original array is repeated up to the new size.

Resize `array_0` to contain 3 rows and 6 columns.

In [ ]:
...

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 0. , 0.1],
       [0.2, 0.3, 0.4, 0.5, 0.6, 0.7]])

👆 Remember that the array is first linearized, then truncated or completed to the new size, then the format is adjusted.

### Adding or removing elements

#### `np.insert`

Insert a new column (axis 1) into `array_0` at position 2 with the value 9.

In [ ]:
...

array([[0. , 0.1, 9. , 0.2, 0.3, 0.4],
       [0.5, 0.6, 9. , 0.7, 0.8, 0.9]])

Repeat the insertion, but with the values ​​8 and 9.

In [ ]:
...

array([[0. , 0.1, 8. , 0.2, 0.3, 0.4],
       [0.5, 0.6, 9. , 0.7, 0.8, 0.9]])

Now insert a row (axis 0) into `array_1` at position 0 with value 9.

In [ ]:
...

array([[9. , 9. , 9. , 9. , 9. ],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

#### `np.delete`

Delete column 2 of `array_0`.

In [ ]:
...

array([[0. , 0.1, 0.3, 0.4],
       [0.5, 0.6, 0.8, 0.9]])

Delete row 1 of `array_1`.

In [ ]:
...

array([[1. , 1.1, 1.2, 1.3, 1.4]])

#### `np.append`

Add `array_1` to the end of `array_0`, on axis 0.

In [ ]:
...

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

👆 The result is the same as `np.concatenate` with `axis=0`.

Add `array_1` to the end of `array_0`, on axis 1.

In [ ]:
...

array([[0. , 0.1, 0.2, 0.3, 0.4, 1. , 1.1, 1.2, 1.3, 1.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 1.5, 1.6, 1.7, 1.8, 1.9]])

👆 The result is the same as `np.concatenate` with `axis=1`.

#### `np.tile`

Use `np.tile` to repeat `array_0`, 2 times on axis 0, and 4 times on axis 1.

In [ ]:
...

array([[0. , 0.1, 0.2, 0.3, 0.4, 0. , 0.1, 0.2, 0.3, 0.4, 0. , 0.1, 0.2,
        0.3, 0.4, 0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 0.5, 0.6, 0.7, 0.8, 0.9, 0.5, 0.6, 0.7,
        0.8, 0.9, 0.5, 0.6, 0.7, 0.8, 0.9],
       [0. , 0.1, 0.2, 0.3, 0.4, 0. , 0.1, 0.2, 0.3, 0.4, 0. , 0.1, 0.2,
        0.3, 0.4, 0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 0.5, 0.6, 0.7, 0.8, 0.9, 0.5, 0.6, 0.7,
        0.8, 0.9, 0.5, 0.6, 0.7, 0.8, 0.9]])

What if you want to repeat `array_0` only 3 times on axis 0?

In [ ]:
...

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

#### `np.pad`

Fill `array_1` with 3 values ​​before and 4 values ​​after. The value must be the constant 0.

In [ ]:
...

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. , 1.1, 1.2, 1.3, 1.4, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1.5, 1.6, 1.7, 1.8, 1.9, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

👆 Added 3 rows and 3 columns "before" `array_1`, and 4 rows/4 columns "after".

Repeat, but filling with the "edge" values.

In [ ]:
...

array([[1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9]])

Repeat with the minimum value.

In [ ]:
...

array([[1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.6, 1.7, 1.8, 1.9, 1.5, 1.5, 1.5, 1.5],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1.1, 1.2, 1.3, 1.4, 1. , 1. , 1. , 1. ]])

Repeat with the maximum value.

In [ ]:
...

array([[1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.4, 1.4, 1.4, 1. , 1.1, 1.2, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9],
       [1.9, 1.9, 1.9, 1.5, 1.6, 1.7, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9]])

#### `np.trim_zeros`

This function only works with 1D arrays.

First create a 1D array with values ​​between 1 and 5, and step = 0.5. Use `np.arange` for this.

In [ ]:
array = ...

In [ ]:
array

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Now use `np.pad` to add 6 values 0 ​​to the left and 4 values 0 ​​to the right of `array`.

In [ ]:
array_pad = ...

In [ ]:
array_pad

array([0. , 0. , 0. , 0. , 0. , 0. , 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ,
       4.5, 0. , 0. , 0. , 0. ])

Apply `np.trim` to `array_pad` to remove the values 0 ​​from the ends, thus recovering `array`.

In [ ]:
array_trim = ...

In [ ]:
array_trim

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Repeat the operation using the `trim` parameter to remove only the "front" (`f`) values 0 ​​from `array_pad`.

In [ ]:
array_trim = ...

In [ ]:
array_trim

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 0. , 0. , 0. , 0. ])

#### `np.unique`

Let's start by creating a large array of random integers, where there will certainly be repetitions.

First, instantiate a random number generator with `np.random.default_rng`. Set the `seed` to the value 75.

In [ ]:
rng = ...

Now generate an array with 200 random integer values ​​in the range [50, 75).

In [ ]:
array_unique = ...

In [ ]:
array_unique

array([66, 55, 55, 53, 73, 66, 58, 67, 68, 73, 58, 68, 69, 73, 69, 73, 67,
       71, 50, 50, 66, 60, 54, 70, 63, 50, 63, 53, 67, 74, 65, 74, 51, 70,
       50, 71, 60, 60, 73, 66, 59, 70, 62, 74, 71, 55, 53, 58, 67, 60, 50,
       54, 69, 74, 68, 72, 69, 56, 67, 52, 51, 70, 68, 54, 71, 54, 57, 69,
       66, 69, 62, 61, 64, 74, 73, 70, 63, 64, 55, 50, 71, 63, 67, 60, 56,
       61, 66, 61, 70, 56, 67, 53, 68, 61, 69, 69, 58, 68, 65, 58, 67, 67,
       57, 69, 63, 68, 66, 70, 68, 74, 60, 62, 50, 66, 72, 66, 66, 55, 73,
       51, 69, 58, 72, 67, 57, 67, 52, 72, 61, 55, 65, 73, 50, 66, 63, 69,
       59, 50, 69, 51, 72, 67, 64, 58, 71, 64, 52, 67, 60, 60, 62, 63, 61,
       67, 61, 57, 60, 57, 73, 62, 74, 71, 57, 62, 58, 59, 72, 71, 62, 67,
       52, 68, 74, 55, 61, 67, 62, 61, 55, 54, 57, 63, 51, 55, 72, 55, 70,
       52, 55, 51, 52, 51, 66, 74, 62, 53, 50, 70, 50, 52])

With a single call to `np.unique`, get:
- theh unique values
- the indices where each value first appears (`return_index` parameter)
- the indices that can be used to reconstruct the original array from theh unique values ​​(`return_inverse` parameter)
- the count of the unique values ​​(`return_counts` parameter)

In [ ]:
unique_values, indices_first, indices_redo, counts = ...

In [ ]:
unique_values

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74])

In [ ]:
indices_first

array([18, 32, 59,  3, 22,  1, 57, 66,  6, 40, 21, 71, 42, 24, 72, 30,  0,
        7,  8, 12, 23, 17, 55,  4, 29])

In [ ]:
indices_redo

array([16,  5,  5,  3, 23, 16,  8, 17, 18, 23,  8, 18, 19, 23, 19, 23, 17,
       21,  0,  0, 16, 10,  4, 20, 13,  0, 13,  3, 17, 24, 15, 24,  1, 20,
        0, 21, 10, 10, 23, 16,  9, 20, 12, 24, 21,  5,  3,  8, 17, 10,  0,
        4, 19, 24, 18, 22, 19,  6, 17,  2,  1, 20, 18,  4, 21,  4,  7, 19,
       16, 19, 12, 11, 14, 24, 23, 20, 13, 14,  5,  0, 21, 13, 17, 10,  6,
       11, 16, 11, 20,  6, 17,  3, 18, 11, 19, 19,  8, 18, 15,  8, 17, 17,
        7, 19, 13, 18, 16, 20, 18, 24, 10, 12,  0, 16, 22, 16, 16,  5, 23,
        1, 19,  8, 22, 17,  7, 17,  2, 22, 11,  5, 15, 23,  0, 16, 13, 19,
        9,  0, 19,  1, 22, 17, 14,  8, 21, 14,  2, 17, 10, 10, 12, 13, 11,
       17, 11,  7, 10,  7, 23, 12, 24, 21,  7, 12,  8,  9, 22, 21, 12, 17,
        2, 18, 24,  5, 11, 17, 12, 11,  5,  4,  7, 13,  1,  5, 22,  5, 20,
        2,  5,  1,  2,  1, 16, 24, 12,  3,  0, 20,  0,  2])

In [ ]:
counts

array([11,  7,  7,  5,  5, 11,  3,  7,  8,  3,  9,  9,  9,  8,  4,  3, 12,
       16,  9, 12,  9,  8,  7,  9,  9])

Does this function work as advertised? 🤔 Use `unique_values` and `indices_redo` to reconstruct the original array.

In [ ]:
...

array([66, 55, 55, 53, 73, 66, 58, 67, 68, 73, 58, 68, 69, 73, 69, 73, 67,
       71, 50, 50, 66, 60, 54, 70, 63, 50, 63, 53, 67, 74, 65, 74, 51, 70,
       50, 71, 60, 60, 73, 66, 59, 70, 62, 74, 71, 55, 53, 58, 67, 60, 50,
       54, 69, 74, 68, 72, 69, 56, 67, 52, 51, 70, 68, 54, 71, 54, 57, 69,
       66, 69, 62, 61, 64, 74, 73, 70, 63, 64, 55, 50, 71, 63, 67, 60, 56,
       61, 66, 61, 70, 56, 67, 53, 68, 61, 69, 69, 58, 68, 65, 58, 67, 67,
       57, 69, 63, 68, 66, 70, 68, 74, 60, 62, 50, 66, 72, 66, 66, 55, 73,
       51, 69, 58, 72, 67, 57, 67, 52, 72, 61, 55, 65, 73, 50, 66, 63, 69,
       59, 50, 69, 51, 72, 67, 64, 58, 71, 64, 52, 67, 60, 60, 62, 63, 61,
       67, 61, 57, 60, 57, 73, 62, 74, 71, 57, 62, 58, 59, 72, 71, 62, 67,
       52, 68, 74, 55, 61, 67, 62, 61, 55, 54, 57, 63, 51, 55, 72, 55, 70,
       52, 55, 51, 52, 51, 66, 74, 62, 53, 50, 70, 50, 52])