In [ ]:
import numpy as np
np.__version__

'1.25.2'

## Ufuncs

Let's start by generating 2 arrays of integers to use in the exercises.

In [ ]:
rng = np.random.default_rng(seed=2)

In [ ]:
array_1 = rng.integers(low=-10, high=10, size=6).reshape(3, 2)
array_1

array([[ 6, -5],
       [-8, -5],
       [-2,  6]])

In [ ]:
array_2 = rng.integers(low=-10, high=10, size=6).reshape(3,2)
array_2

array([[-1, -9],
       [-4,  2],
       [ 6,  4]])

### Mathematical functions

#### `np.add`, `np.subtract`, `np.multiply`, `np.divide`

Use the 4 universal functions corresponding to the basic mathematical operations, using `array_1` and `array_2`, in that order.

Immediately after calling each function, repeat the operation with the native Python mathematical operators, `+`, `-`, `*` and `/`, to verify that the result is the same.

In [ ]:
np....

array([[  5, -14],
       [-12,  -3],
       [  4,  10]])

In [ ]:
... + ...

array([[  5, -14],
       [-12,  -3],
       [  4,  10]])

In [ ]:
...

array([[ 7,  4],
       [-4, -7],
       [-8,  2]])

In [ ]:
...

array([[ 7,  4],
       [-4, -7],
       [-8,  2]])

In [ ]:
...

array([[ -6,  45],
       [ 32, -10],
       [-12,  24]])

In [ ]:
...

array([[ -6,  45],
       [ 32, -10],
       [-12,  24]])

In [ ]:
...

array([[-6.        ,  0.55555556],
       [ 2.        , -2.5       ],
       [-0.33333333,  1.5       ]])

In [ ]:
...

array([[-6.        ,  0.55555556],
       [ 2.        , -2.5       ],
       [-0.33333333,  1.5       ]])

#### `np.mod`

The most common way to check whether a number is *even* is to observe whether its *modulus* when divided by 2 is equal to 0.

Use the `np.mod` function to check the modulus of the `array_1` values ​​when divided by 2.

In [ ]:
array_mod = ...

In [ ]:
array_mod

array([[0, 1],
       [0, 1],
       [0, 0]])

Now use the basic `==` operator to confirm which `array_mod` values ​​are equal to 0.

In [ ]:
...

array([[ True, False],
       [ True, False],
       [ True,  True]])

This comparison indicates which values ​​are even (`True`).

#### `np.divmod`

Many division operations result in "broken" values. Sometimes we want to represent the result as integer values, in a truncated format, where we discard the decimal part.

Use `np.divmod` to check which is the integer part and the remainder when dividing `array_1` by 4.

In [ ]:
array_int, array_rest = ...

In [ ]:
array_int

array([[ 1, -2],
       [-2, -2],
       [-1,  1]])

👆 This array represents the rounding by truncation of the results of the operation.

In [ ]:
array_rest

array([[2, 3],
       [0, 3],
       [2, 2]])

👆 This is the remainder of the division.

#### `np.absolute`

Check what the absolute values ​​of `array_2` are.

In [ ]:
...

array([[1, 9],
       [4, 2],
       [6, 4]])

#### `np.diff`

Check the difference between the values ​​of the columns of `array_1`.

In [ ]:
...

array([[-11],
       [  3],
       [  8]])

Check the difference between the values ​​of the rows of `array_2`.

In [ ]:
...

array([[-3, 11],
       [10,  2]])

#### `np.power`, `np.exp`, `np.log`

Calculate the values ​​of `array_2` cubed.

In [ ]:
...

array([[  -1, -729],
       [ -64,    8],
       [ 216,   64]])

Calculate the value of the natural number *e* raised to the values ​​of `array_1`.

In [ ]:
...

array([[4.03428793e+02, 6.73794700e-03],
       [3.35462628e-04, 6.73794700e-03],
       [1.35335283e-01, 4.03428793e+02]])

Calculate the natural logarithm of the values ​​of `array_2`.

In [ ]:
...

<ipython-input-110-6d7a252fbd89>:1: RuntimeWarning: invalid value encountered in log
  np.log(array_2)


array([[       nan,        nan],
       [       nan, 0.69314718],
       [1.79175947, 1.38629436]])

#### `np.reciprocal`

Determine the reciprocal values ​​of `array_1`. Remember that you need to convert the array values ​​to float first.

In [ ]:
...

array([[ 0.16666667, -0.2       ],
       [-0.125     , -0.2       ],
       [-0.5       ,  0.16666667]])

#### `np.sqrt`, `np.cbrt`

Get the square root of the values ​​of `array_1`.

In [ ]:
...

<ipython-input-112-8db68dfbb9e4>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(array_1)


array([[2.44948974,        nan],
       [       nan,        nan],
       [       nan, 2.44948974]])

Get the cube root of the values ​​from `array_2`.

In [ ]:
...

array([[-1.        , -2.08008382],
       [-1.58740105,  1.25992105],
       [ 1.81712059,  1.58740105]])

#### `np.gcd`, `np.lcm`

Calculate the greatest common divisor and the least common multiple between `array_1` and `array_2`.

In [ ]:
...

array([[1, 1],
       [4, 1],
       [2, 2]])

In [ ]:
...

array([[ 6, 45],
       [ 8, 10],
       [ 6, 12]])

### Trigonometric functions

Calculate the sine, cosine and tangent of some important angles: 30, 45 and 90 degrees. Remember that you need to convert the angle to radians first.

In [ ]:
radians_30 = np....

In [ ]:
np.sin(...)

0.49999999999999994

👆 The exact value is 0.5.

In [ ]:
...

0.8660254037844387

In [ ]:
...

0.5773502691896257

In [ ]:
radians_45 = ...

In [ ]:
...

0.7071067811865475

In [ ]:
...

0.7071067811865476

In [ ]:
...

0.9999999999999999

👆 The exact value is 1.

In [ ]:
radians_90 = ...

In [ ]:
...

1.0

In [ ]:
...

6.123233995736766e-17

👆 The exact value is 0.

In [ ]:
...

1.633123935319537e+16

👆 The exact value is *infinite*, as $$tan(x) = \frac{sin(x)}{cos(x)}$$ and the cosine of 90 degrees is equal to 0. For rounding reasons, the NumPy returns a "very high" value instead of expressing infinity.

### Comparison functions

#### `np.maximum`,  `np.minimum`

Get the maximum and minimum values when comparing `array_1` and `array_2`.

In [ ]:
...

array([[ 6, -5],
       [-4,  2],
       [ 6,  6]])

In [ ]:
...

array([[-1, -9],
       [-8, -5],
       [-2,  4]])

#### `np.greater`,  `np.greater_equal`, `np.less`,  `np.less_equal`,  `np.not_equal`, `np.equal`

Compare `array_1` with `array_2` to check if their values ​​are...

... larger:

In [ ]:
...

array([[ True,  True],
       [False, False],
       [False,  True]])

... smaller or equal:

In [ ]:
...

array([[False, False],
       [ True,  True],
       [ True, False]])

... different:

In [ ]:
...

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

#### `logical_and`, `logical_or`, `logical_xor`, `logical_not`

First generate a boolean mask to check which values ​​in `array_1` and `array_2` are even.

In [ ]:
array_1_mask = ...

In [ ]:
array_1_mask

array([[ True, False],
       [ True, False],
       [ True,  True]])

In [ ]:
array_2_mask = ...

In [ ]:
array_2_mask

array([[False, False],
       [ True,  True],
       [ True,  True]])

Now, with `logical_and`, check where in both arrays the values ​​are even.

In [ ]:
...

array([[False, False],
       [ True, False],
       [ True,  True]])

With `logical_or` you can check where at least one of the values ​​is even.

In [ ]:
...

array([[ True, False],
       [ True,  True],
       [ True,  True]])

You can also check where at least one of the values ​​is odd with `logical_not`, without having to redo the boolean masks.

In [ ]:
...

array([[False,  True],
       [False,  True],
       [False, False]])

#### `np.isclose`, `np.allclose`

Now let's generate 2 new arrays with real values ​​from sampling a normal distribution, with a small standard deviation.

In [ ]:
array_3 = rng.normal(loc=0, scale=0.0001, size=6).reshape(3, 2)

In [ ]:
array_3

array([[-3.25422837e-05,  7.73806587e-05],
       [ 2.81210670e-05, -5.53822836e-05],
       [ 9.77567451e-05, -3.10556547e-05]])

In [ ]:
array_4 = rng.normal(loc=0, scale=0.0001, size=6).reshape(3, 2)

In [ ]:
array_4

array([[-3.28823904e-05, -7.92146755e-05],
       [ 4.54958071e-05, -9.91980517e-06],
       [ 5.45288714e-05, -6.07185700e-05]])

Check whether the values ​​of `array_3` are close to `array_4` within the 0.001 tolerance margin.

In [ ]:
...

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

Check whether all values ​​meet this condition.

In [ ]:
...

True

👆 All values ​​are the same within this tolerance range.

What if the tolerance margin is equal to 0.0001?

In [ ]:
...

array([[ True, False],
       [ True,  True],
       [ True,  True]])

In [ ]:
...

False

👆 Not all values ​​are equal within this tolerance range.

#### `np.array_equal`

Generate a **view** of `array_3` and confirm that the view is equal to the array, with the `np.array_equal` function.

In [ ]:
array_3_view = ...

In [ ]:
...

True

### Float functions

#### `np.isfinite`, `np.isinf`, `np.isneginf`, `np.isnan`

Start by generating an array with random integer values ​​in the range [-10, 11), organized into an array in the format (3, 4).

In [ ]:
array_5 = ...

In [ ]:
array_5

array([[ -3,  -2, -10,  -7],
       [ -4,  -3,   2,   0],
       [  4,   8,   8,   6]])

Now generate a new array with only values ​​0 or 1, in the same format. You can also use `rng.integers` for this.

In [ ]:
array_6 = ...

In [ ]:
array_6

array([[1, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 0, 0, 0]])

Determine the division of `array_5` by `array_6`.

In [ ]:
array_div = ...

<ipython-input-154-171e7efd37aa>:1: RuntimeWarning: divide by zero encountered in divide
  array_div = np.divide(array_5, array_6)


In [ ]:
array_div

array([[ -3., -inf, -10.,  -7.],
       [-inf, -inf,   2.,   0.],
       [  4.,  inf,  inf,  inf]])

Check which values in `array_div` ​​are:

... finite:

In [ ]:
...

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [ True, False, False, False]])

... infinite:

In [ ]:
...

array([[False,  True, False, False],
       [ True,  True, False, False],
       [False,  True,  True,  True]])

... negative infinite:

In [ ]:
...

array([[False,  True, False, False],
       [ True,  True, False, False],
       [False, False, False, False]])

Now determine the logarithm in base 10 of `array_5`.

In [ ]:
array_log_10 = ...

<ipython-input-159-3664a7768494>:1: RuntimeWarning: divide by zero encountered in log10
  array_log_10 = np.log10(array_5)
<ipython-input-159-3664a7768494>:1: RuntimeWarning: invalid value encountered in log10
  array_log_10 = np.log10(array_5)


In [ ]:
array_log_10

array([[       nan,        nan,        nan,        nan],
       [       nan,        nan, 0.30103   ,       -inf],
       [0.60205999, 0.90308999, 0.90308999, 0.77815125]])

Which of these values ​​are indeterminate ("not a number")?

In [ ]:
...

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

### Float functions

#### `np.floor`, `np.ceil`, `np.trunc`

Generate a new array with 10 random values ​​obtained from a normal distribution, with mean 0 and standard deviation 1.

In [ ]:
array_7 = ...

In [ ]:
array_7

array([ 0.84145889,  0.12871566,  1.07834244,  0.72243087,  0.21057181,
        0.28403815, -0.1697605 ,  0.86846021, -1.12971596, -0.42185883])

Round the values...

... down:

In [ ]:
...

array([ 0.,  0.,  1.,  0.,  0.,  0., -1.,  0., -2., -1.])

... up:

In [ ]:
...

array([ 1.,  1.,  2.,  1.,  1.,  1., -0.,  1., -1., -0.])

... the integer closest to 0:

In [ ]:
...

array([ 0.,  0.,  1.,  0.,  0.,  0., -0.,  0., -1., -0.])