In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.25.2'

In this module, you will be invited to redo some of the examples presented in class, to consolidate the concepts.

### NumPy x Lists

#### Fixed size

Below we will instantiate an array with 4 elements.

In [ ]:
array_a = np.array([0, 1, 2, 3])

Using the `np.append` function, add the element `4` at the end of this array. Remember that this new element must be "enveloped" in a list: `[4]`. Put the result in new array called `array_b` and display the result.

In [ ]:
array_b = ...

In [ ]:
array_b

array([0, 1, 2, 3, 4])

Now, using Python's `id` function and the `==` comparator, show that the two arrays have different addresses in memory, which shows that `array_b` is different from `array_a`.

💡 This is because, in NumPy, arrays have a **fixed size**. If you add elements to the array, a new array is created.

In [ ]:
...

False

#### Homogeneous

Instantiate an array `array_c` with 3 elements:
- the number `3` (integer)
- the number `7.9` (float)
- the value `False` (boolean)

Display this array.

In [ ]:
array_c = ...

In [ ]:
array_c

array([3. , 7.9, 0. ])

Using a `for` loop to iterate over the elements of `array_c`, display on the screen (`print`) the element itself, and the type of each element in the array, using the `type` function.

In [ ]:
for ...
    print(..., ...)

3.0 <class 'numpy.float64'>
7.9 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>


💡 Note that to maintain the homogeneity of the array, all elements were converted to type `np.float`.

Now, using the array's `dtype` method, display the type of data it stores.

In [ ]:
...

dtype('float64')

💡 Note that the array has the same data type as its elements.

#### Vectorization

Instantiate an array `array_d` with the values ​​`10`, `11`, `12` and `13`, and an array `array_e` with the values ​​`1`, `2`, `3` and `4`.

Display these two arrays.

In [ ]:
array_d = ...
array_e = ...

array_d, array_e

(array([10, 11, 12, 13]), array([1, 2, 3, 4]))

Now, perform the 4 basic mathematical operations (addition, subtraction, multiplication and division) using the native Python operators (`+`, `-`, `*`, `/`). Display the results directly, without storing them in a variable first.

In [ ]:
... + ...

array([11, 13, 15, 17])

In [ ]:
...

array([9, 9, 9, 9])

In [ ]:
...

array([10, 22, 36, 52])

In [ ]:
...

array([10.  ,  5.5 ,  4.  ,  3.25])

💡 The use of basic operators is only possible thanks to the vector nature of NumPy arrays, which allows element-by-element mathematical operations between arrays.

#### Broadcasting

Let's reuse `array_d` to demonstrate the broadcasting property.

Use the 4 basic mathematical operators to add, subtract, multiply and divide the value `2` of each element in the array.

Print results directly to the screen.

In [ ]:
... + 2

array([12, 13, 14, 15])

In [ ]:
...

array([ 8,  9, 10, 11])

In [ ]:
...

array([20, 22, 24, 26])

In [ ]:
...

array([5. , 5.5, 6. , 6.5])

💡 Note that, if you want to perform these operations on all elements of the array with a **fixed value**, you can use this value as a scalar, without the need to transform it into an array. This is possible thanks to the broadcasting property.